const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const categoriaSchema = new Schema({
    Categoria: String,
    Modalidad: String,
    Genero: String,
    Disciplina: String,
    Division: String,
    DesdeEdad: Number,
    HastaEdad: Number,
    DesdePeso: Number,
    HastaPeso: Number,
    DesdeEstatura: Number,
    HastaEstatura: Number,
    Competidor: [{
        FechaActual: Date, 
        IDFDFF: String,
        Nombre: String,
        Cedula: String,
        Nacimiento: Date,
        Edad: Number,
        Sexo: String,
        Peso: Number,
        Estatura: Number, 
        Sector: String,
        Preparador: String,
        EstadisticasEliminatoria: [{
            J1: Number,
            J2: Number,
            J3: Number,
            J4: Number,
            J5: Number,
            J6: Number,
            J7: Number,
            J8: Number,
            J9: Number,
            J10: Number,
            J11: Number,
            J12: Number,
            J13: Number,
            Total: Number,
            Posicion: Number,
        }],
        EstadisticasSemiFinalR1: [{
            J1: Number,
            J2: Number,
            J3: Number,
            J4: Number,
            J5: Number,
            J6: Number,
            J7: Number,
            J8: Number,
            J9: Number,
            J10: Number,
            J11: Number,
            J12: Number,
            J13: Number,
            Total: Number,
            Posicion: Number,
        }],   
        EstadisticasSemiFinalR2: [{
            J1: Number,
            J2: Number,
            J3: Number,
            J4: Number,
            J5: Number,
            J6: Number,
            J7: Number,
            J8: Number,
            J9: Number,
            J10: Number,
            J11: Number,
            J12: Number,
            J13: Number,
            Total: Number,
            Posicion: Number,
        }], 
        EstadisticasFinalR1: [{
            J1: Number,
            J2: Number,
            J3: Number,
            J4: Number,
            J5: Number,
            J6: Number,
            J7: Number,
            J8: Number,
            J9: Number,
            J10: Number,
            J11: Number,
            J12: Number,
            J13: Number,
            Total: Number,
            Posicion: Number,
        }], 
        EstadisticasFinalR2: [{
            J1: Number,
            J2: Number,
            J3: Number,
            J4: Number,
            J5: Number,
            J6: Number,
            J7: Number,
            J8: Number,
            J9: Number,
            J10: Number,
            J11: Number,
            J12: Number,
            J13: Number,
            Total: Number,
            Posicion: Number,

        }],
        EstadisticasAbsoluto: [{
            J1: Number,
            J2: Number,
            J3: Number,
            J4: Number,
            J5: Number,
            J6: Number,
            J7: Number,
            J8: Number,
            J9: Number,
            J10: Number,
            J11: Number,
            J12: Number,
            J13: Number,
            Total: Number,
            Posicion: Number,
            
        }],
    }]
})


// crear modelo
const Categoria = mongoose.model('Categoria', categoriaSchema);


module.exports = Categoria;


